local util = require "util"

util.map("n", "<leader>r", "<cmd>Cargo run<cr>", "run primary binary")
util.map("n", "<leader>ac", "<cmd>Cargo check<cr>", "check project")
util.map("n", "<leader>al", "<cmd>Cargo clippy -- -D clippy::pedantic<cr>", "lint with clippy")
util.map("n", "<leader>ab", "<cmd>Cargo build<cr>", "build project")
util.map("n", "<leader>ad", "<cmd>Cargo doc<cr>", "build docs")
util.map("n", "<leader>a<C-d>", "<cmd>Cargo doc --open<cr>", "build and open docs")
util.map("n", "<leader>ap", function()
  util.input(function(dep)
    vim.cmd.Cargo("add " .. dep)
  end, { prompt = "Add dependency: " })
end, "add crate(s)")
util.map("n", "<leader>a<C-p>", function()
  util.input(function(dep)
    vim.cmd.Cargo("remove " .. dep)
  end, { prompt = "Remove dependency: " })
end, "remove crate(s)")
