"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$c\
$rust\
$python\
$docker_context\
$character"""

palette = 'kanagawa_dragon'

[palettes.kanagawa_dragon]
color_fg0 = '#c5c9c5'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#658594'
color_aqua = '#8ea4a2'
color_green = '#87a987'
color_orange = '#b6927b'
color_purple = '#8992a7'
color_red = '#c4746e'
color_yellow = '#c4b28a'

[directory]
truncate_to_repo = false

[c]
symbol = ""
style = 'fg:color_blue'
format = '[$symbol]($style)'

[rust]
symbol = ""
style = 'fg:color_orange'
format = '[$symbol]($style)'

[python]
symbol = ""
style = 'fg:color_yellow'
format = '[$symbol]($style)'
detect_extensions = []

[docker_context]
symbol = ""
style = 'fg:color_aqua'
format = '[$symbol]($style)'

[character]
format = ' $symbol '
