# name: Kanagawa
# preferred_background: black

# Syntax Highlighting Colors
fish_color_normal DCD7BA normal
fish_color_command 7AA89F cyan --bold
fish_color_keyword D27E99 brmagenta
fish_color_quote C0A36E yellow --italics
fish_color_redirection DCD7BA normal
fish_color_end FF9E64 brred
fish_color_error C34043 red
fish_color_param 957FB8 magenta
fish_color_valid_path C0A36E yellow --underline
fish_color_comment 727169 brblack --italics
fish_color_selection --background=2D4F67 brcyan
fish_color_search_match --background=2D4F67 brcyan
fish_color_operator 76946A green
fish_color_escape D27E99 brmagenta
fish_color_autosuggestion 727169 brblack --italics

# Completion Pager Colors
fish_pager_color_progress 727169 brblack
fish_pager_color_prefix 7AA89F cyan --underline --bold
fish_pager_color_completion DCD7BA normal
fish_pager_color_description 727169 brblack --italics
